### ISSUE TITLE
支持x32位问题

### ISSUE THREAD

**Issue by S9MF** [snnxyss/new_in_swor#1]
大佬我看你最新的in_swor.exe是64位的，这个支持32位吗

**Comment by snnxyss** [comment]
不支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月15日(周五) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [snnxyss/new_in_swor] 支持x32位问题 (Issue #1)




 
大佬我看你最新的in_swor.exe是64位的，这个支持32位吗
